### ISSUE TITLE
Art page allows you to click hexagons

### ISSUE THREAD

**Issue by wrussell1999** [HHEU/wiki#73]
When clicking hexagons, it tries to open the JSON data but instead returns a 404.

**Comment by bahorn** [comment]
Literally was just working on this right now!

**Comment by wrussell1999** [comment]
You're just too good 😍

**Comment by bahorn** [comment]
https://github.com/HHEU/hexbin/pull/9

Changes made in this PR. just needs some testing before being merged.

**Comment by wrussell1999** [comment]
I'll review it for you!

**Comment by ksouthern** [comment]
The clicking on hexagon issue is resolved with @bahorn 's  PR on hexbin.
However, whilst it works on the local version (with hexbin) it has a slight bug now its been deployed on hack.athon.uk

**Comment by ksouthern** [comment]
Latest fix to hexbin has fixed it. (also it looks incredible @bahorn )
