### ISSUE TITLE
Logo SVG font missing

### ISSUE THREAD

**Issue by jmsv** [HHEU/wiki#82]
Something I noticed while checking out the deploy preview for #77

Homepage [logo SVG](https://github.com/HHEU/wiki/blob/master/docs/static/logo.svg) uses `font-family:'Ubuntu Mono derivative Powerline'` which doesn't render if not installed & falls back to Times New Roman.

SVG should be converted to paths, or a new logo (maybe something closer to the [sticker design](https://twitter.com/baahorn/status/1200699687206039552?s=20)) could be designed

**Comment by bahorn** [comment]
Ah that explains why when that happened when I ran it through some browser testing sites.

But yeah, a better logo should be designed as this was something I hacked up early on.
